// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using desafioPottencialSeguradora.Context;

#nullable disable

namespace desafioPottencialSeguradora.Migrations
{
    [DbContext(typeof(VendaContext))]
    [Migration("20220912184237_CriacaoTabelaVenda")]
    partial class CriacaoTabelaVenda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("desafioPottencialSeguradora.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Itens")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("desafioPottencialSeguradora.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DadosDoVendedorId")
                        .HasColumnType("int");

                    b.Property<int?>("ItensVendidosId")
                        .HasColumnType("int");

                    b.Property<int>("StatusDaVenda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DadosDoVendedorId");

                    b.HasIndex("ItensVendidosId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("desafioPottencialSeguradora.Entities.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("desafioPottencialSeguradora.Entities.Venda", b =>
                {
                    b.HasOne("desafioPottencialSeguradora.Entities.Vendedor", "DadosDoVendedor")
                        .WithMany()
                        .HasForeignKey("DadosDoVendedorId");

                    b.HasOne("desafioPottencialSeguradora.Entities.Pedido", "ItensVendidos")
                        .WithMany()
                        .HasForeignKey("ItensVendidosId");

                    b.Navigation("DadosDoVendedor");

                    b.Navigation("ItensVendidos");
                });
#pragma warning restore 612, 618
        }
    }
}
